### ISSUE TITLE
Error with 6.0.2 and Foreman 1.18 RC3

### ISSUE THREAD

**Issue by treydock** [theforeman/foreman_templates#101] opened 2018-07-06 12:53 UTC
I just upgraded a test system to 1.18 RC3 and foreman_templates 6.0.2 and am getting an error running the rake task for import:

```
[root@foreman-test ~]# foreman-rake templates:import
/usr/share/foreman/lib/core_extensions.rb:182: warning: already initialized constant ActiveSupport::MessageEncryptor::DEFAULT_CIPHER
/opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/message_encryptor.rb:22: warning: previous definition of DEFAULT_CIPHER was here
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_templates-6.0.2/lib/tasks/foreman_templates_tasks.rake:34:in `to_h'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_templates-6.0.2/lib/tasks/foreman_templates_tasks.rake:34:in `block (3 levels) in <top (required)>'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_templates-6.0.2/lib/tasks/foreman_templates_tasks.rake:34:in `each'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_templates-6.0.2/lib/tasks/foreman_templates_tasks.rake:34:in `map'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_templates-6.0.2/lib/tasks/foreman_templates_tasks.rake:34:in `block (2 levels) in <top (required)>'
/opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => templates:import
(See full trace by running task with --trace)
```

**Comment by xprazak2** [comment] 2018-07-17 13:04
Thanks for reporting this, I am closing as the issue is tracked under https://projects.theforeman.org/issues/24208.

**Closed by xprazak2** 2018-07-17 13:04 UTC
